name: cloud

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ProjetoCloud
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DATABASE_URL: "postgresql://postgres:1234@db:5432/ProjetoCloud"
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: always
